name: 无忧行签到

on:
  push:
  schedule:
    - cron: '0 0,1 * * *'

jobs:
  autosign:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'

      - name: 'Sign'
        env:
          TASKID: ${{ secrets.TASKID }}
          USERID: ${{ secrets.USERID }}
        run: php wuyouxing.php
